const incidents=[
{id:"INC-10621",rule:"INC-002",critical:true,store:"Магазин № 184",city:"Екатеринбург",cash:"Касса 04",type:"Реализован товар с истекшим сроком годности",group:"Молочная продукция",time:"28.07.2026, 17:42",result:"Подтверждённое нарушение",contour:"SetRetail",fine:20000,mark:"010460123456781721ABCD92",status:"Анализ завершён",reason:"Касса получила от онлайн-сервиса Честного Знака корректное значение expireDate, срок годности уже истёк, но продажа была завершена.",recommendation:"Обратиться в техническую поддержку CSI: при корректно разобранном истёкшем expireDate штатная проверка должна блокировать продажу.",sourceKind:"38 — Реализован товар с истекшим сроком годности",sourceText:"Онлайн ЧЗ вернул expireDate; значение успешно распознано и было меньше либо равно времени проверки.",chain:["Получен онлайн-ответ ЧЗ с полем expireDate.","expireDate успешно распознан; срок годности истёк.","Продажа завершена успешно вопреки штатной блокировке."]},
{id:"INC-10608",rule:"INC-002",critical:true,store:"Магазин № 052",city:"Пермь",cash:"Касса 11",type:"Реализован товар с истекшим сроком годности",group:"Молочная продукция",time:"28.07.2026, 16:18",result:"Подтверждённое нарушение",contour:"Настройки магазина",fine:20000,mark:"010460123456782728EFGH41",status:"Анализ завершён",reason:"Честный Знак вернул expireDate, но касса не смогла разобрать значение и настройка разрешила продолжить продажу.",recommendation:"Запретить продажу, если касса не получила срок годности или не смогла корректно распознать его в ответе Честного Знака. Установить check.excise.ignoreTrueApiMarkIncorrectExpirationDate = false.",sourceKind:"38 — Реализован товар с истекшим сроком годности",sourceText:"Поле expireDate получено, но касса зарегистрировала ошибку разбора формата.",chain:["Получен онлайн-ответ ЧЗ с полем expireDate.","Значение expireDate не удалось разобрать.","Настройка разрешила продажу при некорректном значении срока годности."]},
{id:"INC-10597",rule:"INC-002",critical:false,store:"Магазин № 317",city:"Тюмень",cash:"Касса 02",type:"Реализован товар с истекшим сроком годности",group:"Молочная продукция",time:"27.07.2026, 12:56",result:"Подтверждённое нарушение",contour:"Внешний бизнес-процесс",fine:0,mark:"010460123456783725JKLM73",status:"Анализ завершён",reason:"Онлайн ЧЗ был недоступен. Продажа законно выполнена по разрешающему ответу ЛМ ЧЗ, который не возвращает срок годности.",recommendation:"Для полного исключения риска отключить ЛМ ЧЗ и выполнять проверки только через онлайн ЧЗ. Важно: при недоступности онлайн ЧЗ продажи маркированных товаров будут заблокированы.",sourceKind:"38 — Реализован товар с истекшим сроком годности",sourceText:"Отклонение сформировано позднее; до продажи явный истёкший expireDate кассой не получен.",chain:["Онлайн-сервис ЧЗ был недоступен.","ЛМ ЧЗ дал разрешающий ответ без данных о сроке годности.","Продажа завершена; позднее ЧЗ установил, что товар был просрочен."]},
{id:"INC-10541",rule:"INC-001",critical:false,store:"Магазин № 088",city:"Челябинск",cash:"Касса 07",type:"Повторные продажи у одного продавца более или равно 30 минут",group:"Молочная продукция",time:"26.07.2026, 21:04",result:"Допустимый сценарий",contour:"Внешний бизнес-процесс",fine:0,mark:"010460123456785729STUV66",status:"Анализ завершён",reason:"Между первой и повторной продажей в SetRetail найден успешный возврат. Нарушение торговой сети по доступным данным не подтверждено.",recommendation:"Найти чек возврата в ОФД. Если чека нет — обратиться в поддержку CSI; если чек есть, но отклонение сохраняется — в поддержку Честного Знака.",sourceKind:"36 — Повторные продажи у одного продавца более или равно 30 минут",sourceText:"Честный Знак зарегистрировал повторную реализацию одного кода маркировки.",chain:["Найдена первая продажа кода маркировки.","Между продажами найден успешный возврат в SetRetail.","Повторная продажа не подтверждена как нарушение торговой сети."]},
{id:"INC-10512",rule:"INC-001",critical:false,store:"Магазин № 052",city:"Пермь",cash:"Касса 03",type:"Повторные продажи у одного продавца более или равно 30 минут",group:"Обувь",time:"25.07.2026, 18:21",result:"Подтверждённое нарушение",contour:"SetRetail",fine:0,mark:"010460123456786726WXYZ04",status:"Анализ завершён",reason:"Первая и повторная продажи выполнены в разных магазинах с отдельными экземплярами Set Mark Centrum; локальный экземпляр не располагал данными другого магазина.",recommendation:"Перейти с отдельных экземпляров Set Mark Centrum в магазинах на централизованный Set Mark Centrum для торговой сети.",sourceKind:"36 — Повторные продажи у одного продавца более или равно 30 минут",sourceText:"Между продажами возврат не найден; повторная продажа подтверждена.",chain:["Подтверждены две продажи одного кода маркировки.","Возврат между продажами отсутствует.","Продажи выполнены в магазинах с отдельными экземплярами Set Mark Centrum."]},
{id:"INC-10488",rule:"INC-001",critical:false,store:"Магазин № 241",city:"Уфа",cash:"Касса 09",type:"Повторные продажи у одного продавца более или равно 30 минут",group:"Упакованная вода",time:"24.07.2026, 13:39",result:"Подтверждённое нарушение",contour:"Настройки магазина",fine:0,mark:"010460123456787723BCDF39",status:"Анализ завершён",reason:"Для товарной категории «Упакованная вода» была отключена проверка в Set Mark, поэтому повторная продажа не была заблокирована.",recommendation:"В настройках Set Mark включить проверку товарной категории «Упакованная вода».",sourceKind:"36 — Повторные продажи у одного продавца более или равно 30 минут",sourceText:"Между продажами возврат не найден; повторная продажа подтверждена.",chain:["Подтверждены две продажи одного кода маркировки.","Возврат между продажами отсутствует.","Проверка товарной категории «Упакованная вода» в Set Mark отключена."]},
{id:"INC-10462",rule:"INC-006",critical:false,store:"Магазин № 184",city:"Екатеринбург",cash:"Касса 01",type:"Продажа товара без проверки КМ",group:"Пиво",time:"23.07.2026, 10:12",result:"Подтверждённое нарушение",contour:"Настройки магазина",fine:0,mark:"010460123456784722NPQR18",status:"Анализ завершён",reason:"В наших данных чека квитанция проверки отсутствует. Для товарной группы «Пиво» отключена обязательная проверка.",recommendation:"В процессинге «Валидация в сервисе Честный знак» включить настройку «Валидировать пиво».",sourceKind:"48 — Продажа товара без проверки КМ",sourceText:"В данных позиции маркированного товара отсутствует квитанция онлайн ЧЗ или ЛМ ЧЗ.",chain:["Получено отклонение ЧЗ об отсутствии проверки КМ.","В нашем кассовом чеке квитанция также отсутствует.","Настройка «Валидировать пиво» в текущей конфигурации отключена."]},
{id:"INC-10437",rule:"INC-006",critical:false,store:"Магазин № 317",city:"Тюмень",cash:"Касса 05",type:"Продажа товара без проверки КМ",group:"Безалкогольные напитки",time:"22.07.2026, 19:03",result:"Подтверждённое нарушение",contour:"Настройки магазина",fine:0,mark:"010460123456788720GHJK52",status:"Анализ завершён",reason:"В наших данных чека квитанция отсутствует. Настройка разрешала продажу при отсутствии ответа от ЧЗ.",recommendation:"Отключить настройку «Разрешить продажу при отсутствии ответа от ЧЗ».",sourceKind:"48 — Продажа товара без проверки КМ",sourceText:"В данных позиции маркированного товара отсутствует квитанция онлайн ЧЗ или ЛМ ЧЗ.",chain:["Получено отклонение ЧЗ об отсутствии проверки КМ.","В нашем кассовом чеке квитанция также отсутствует.","Продажа без ответа сервисов проверки была разрешена настройкой."]},
{id:"INC-10411",rule:"INC-006",critical:false,store:"Магазин № 052",city:"Пермь",cash:"Касса 08",type:"Продажа товара без проверки КМ",group:"Молочная продукция",time:"22.07.2026, 14:28",result:"Допустимый сценарий",contour:"Честный Знак",fine:0,mark:"010460123456789727LMNP27",status:"Анализ завершён",reason:"В наших данных кассового чека присутствует сохранённая квитанция проверки КМ. Нарушение ритейлера по доступным данным не подтверждено.",recommendation:"Обратиться в техническую поддержку Честного Знака, приложив отклонение, кассовый чек, полный код маркировки и сохранённую квитанцию проверки.",sourceKind:"48 — Продажа товара без проверки КМ",sourceText:"Честный Знак сообщил об отсутствии проверки, однако квитанция сохранена в данных SetRetail.",chain:["Получено отклонение ЧЗ об отсутствии проверки КМ.","В нашем кассовом чеке квитанция проверки присутствует.","Причина расхождения не определяется; проверка ОФД в v0.1 не выполняется."]}
];
const incidentProductData={
"INC-10621":{barcode:"4601234567817",article:"MILK-001",product:"Молоко пастеризованное 3,2%, 1 л",receipt:"Чек 621",verificationSource:"Онлайн ЧЗ"},
"INC-10608":{barcode:"4601234567824",article:"YOG-052",product:"Йогурт натуральный, 150 г",receipt:"Чек 608",verificationSource:"Онлайн ЧЗ"},
"INC-10597":{barcode:"4601234567831",article:"KEF-317",product:"Кефир 2,5%, 1 л",receipt:"Чек 597",verificationSource:"ЛМ ЧЗ"},
"INC-10541":{barcode:"4601234567855",article:"CHEESE-088",product:"Сыр полутвёрдый, 200 г",receipt:"Чек 541",verificationSource:"SetRetail / ЧЗ"},
"INC-10512":{barcode:"4601234567862",article:"SHOE-052",product:"Кроссовки повседневные",receipt:"Чек 512",verificationSource:"SetRetail / ЧЗ"},
"INC-10488":{barcode:"4601234567879",article:"WATER-241",product:"Вода питьевая, 1,5 л",receipt:"Чек 488",verificationSource:"SetRetail / ЧЗ"},
"INC-10462":{barcode:"4601234567848",article:"BEER-184",product:"Пиво светлое, 0,5 л",receipt:"Чек 462",verificationSource:"Онлайн ЧЗ"},
"INC-10437":{barcode:"4601234567886",article:"DRINK-317",product:"Напиток безалкогольный, 0,5 л",receipt:"Чек 437",verificationSource:"Онлайн ЧЗ"},
"INC-10411":{barcode:"4601234567893",article:"MILK-052",product:"Молоко ультрапастеризованное, 1 л",receipt:"Чек 411",verificationSource:"Онлайн ЧЗ"}
};
incidents.forEach(i=>Object.assign(i,incidentProductData[i.id]));
const actions=[
{text:"Запретить продажу, если касса не получила срок годности или не смогла корректно распознать его в ответе Честного Знака. Установить check.excise.ignoreTrueApiMarkIncorrectExpirationDate = false.",incidentIds:["INC-10608"],critical:true},
{text:"Обратиться в техническую поддержку CSI по факту продажи после корректно распознанного истёкшего expireDate.",incidentIds:["INC-10621"],critical:true},
{text:"Отключить ЛМ ЧЗ и выполнять проверки только через онлайн ЧЗ, приняв риск остановки продаж при недоступности сервиса.",incidentIds:["INC-10597"],critical:false},
{text:"Перейти на централизованный Set Mark Centrum для торговой сети.",incidentIds:["INC-10512"],critical:false},
{text:"В настройках Set Mark включить проверку товарной категории «Упакованная вода».",incidentIds:["INC-10488"],critical:false},
{text:"В процессинге «Валидация в сервисе Честный знак» включить настройку «Валидировать пиво».",incidentIds:["INC-10462"],critical:false},
{text:"Отключить настройку «Разрешить продажу при отсутствии ответа от ЧЗ».",incidentIds:["INC-10437"],critical:false},
{text:"Обратиться в техническую поддержку Честного Знака с сохранённой квитанцией проверки.",incidentIds:["INC-10411"],critical:false}
].map(a=>({...a,count:a.incidentIds.length})).sort((a,b)=>Number(b.critical)-Number(a.critical)||b.count-a.count);
const state={query:"",priorityOnly:false,confirmedOnly:false,result:"",stores:[],types:[],actionIncidentIds:null,tab:"analysis",rangePreset:"week",rangeStart:"2026-07-22",rangeEnd:"2026-07-28"};
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)],fmt=n=>new Intl.NumberFormat("ru-RU").format(n),DAY=86400000;
function badge(t,c="neutral"){return `<span class="badge ${c}">${t}</span>`}function toast(t){const e=qs("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}function navigate(h){location.hash=h}function dateAtStart(v){return new Date(`${v}T00:00:00`)}function incidentDate(v){const[d]=v.split(","),[a,b,c]=d.split(".").map(Number);return new Date(c,b-1,a)}
function pageHead(t,s,a=""){return `<div class="page-head"><div><h1>${t}</h1><p>${s}</p><span class="freshness">Обновлено сегодня в 18:40 · UTC+05:00</span></div><div class="controls">${a}</div></div>`}
function dateRangeLabel(){const f=new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",year:"numeric"});return `${f.format(dateAtStart(state.rangeStart))} — ${f.format(dateAtStart(state.rangeEnd))}`}
function dateRangeControl(){return `<div class="date-range"><label><span>Период</span><select class="select" data-range-preset><option value="today" ${state.rangePreset==="today"?"selected":""}>Сегодня</option><option value="week" ${state.rangePreset==="week"?"selected":""}>Неделя</option><option value="month" ${state.rangePreset==="month"?"selected":""}>30 дней</option><option value="custom" ${state.rangePreset==="custom"?"selected":""}>Произвольный</option></select></label><div class="custom-range" ${state.rangePreset==="custom"?"":"hidden"}><label><span>С</span><input class="input date-input" data-range-start type="date" value="${state.rangeStart}"></label><span>—</span><label><span>По</span><input class="input date-input" data-range-end type="date" value="${state.rangeEnd}"></label><button class="button" data-apply-range>Применить</button></div></div>`}
function applyPreset(p){const end="2026-07-28",days={today:0,week:6,month:29}[p];if(days===undefined)return;const s=dateAtStart(end);s.setDate(s.getDate()-days);state.rangePreset=p;state.rangeStart=s.toISOString().slice(0,10);state.rangeEnd=end;route()}
function searchTokens(){return state.query.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean)}
function matchesQuery(i){const tokens=searchTokens();if(!tokens.length)return true;const exact=[i.barcode,i.article,i.mark].map(x=>String(x||"").toLowerCase()),text=[i.id,i.store,i.cash,i.type,i.group,i.product].join(" ").toLowerCase();return tokens.some(t=>exact.includes(t)||text.includes(t))}
function filteredIncidents(){return incidents.filter(i=>(!state.actionIncidentIds||state.actionIncidentIds.includes(i.id))&&(!state.priorityOnly||i.critical)&&(!state.confirmedOnly||i.result==="Подтверждённое нарушение")&&(!state.result||i.result===state.result)&&incidentDate(i.time)>=dateAtStart(state.rangeStart)&&incidentDate(i.time)<=dateAtStart(state.rangeEnd)&&(!state.stores.length||state.stores.includes(i.store))&&(!state.types.length||state.types.includes(i.type))&&matchesQuery(i))}
function metricsForRange(){const r=incidents.filter(i=>incidentDate(i.time)>=dateAtStart(state.rangeStart)&&incidentDate(i.time)<=dateAtStart(state.rangeEnd));return{total:r.length,critical:r.filter(i=>i.critical).length,potentialFine:r.reduce((s,i)=>s+i.fine,0)}}
function actionRow(a){return `<article class="action-row ${a.critical?"priority":""}" tabindex="0" role="button" data-action-incidents="${a.incidentIds.join(",")}"><div><strong>${a.text}</strong><span class="action-meta">${a.critical?badge("Предотвращает критические инциденты","danger"):""} Связано: ${a.count} инцидент</span></div><span>›</span></article>`}
function typeCounts(){return [...new Set(incidents.map(i=>i.type))].map(type=>({type,count:incidents.filter(i=>i.type===type).length})).sort((a,b)=>b.count-a.count)}function typeChart(){const d=typeCounts(),m=Math.max(...d.map(x=>x.count));return `<div class="type-chart">${d.map(x=>`<button class="type-row" data-type-jump="${x.type}"><strong>${x.type}</strong><span class="type-bar"><i style="width:${x.count/m*100}%"></i></span><span>${x.count}</span></button>`).join("")}</div>`}
function renderOverview(){const m=metricsForRange();qs("#overview-view").innerHTML=`${pageHead("Мониторинг нарушений",`Сводка по сети «Север» за ${dateRangeLabel()}`,`${dateRangeControl()}<button class="button" data-export>Выгрузить CSV</button>`)}<section class="priority-banner" id="priority"><div class="priority-icon">!</div><div><h2 id="priority-title">Критические инциденты</h2><p>Инциденты, для которых возможен автоштраф</p></div><div><span class="priority-count">${m.critical}</span><button class="priority-action" data-priority>Перейти к инцидентам →</button></div></section><div class="metrics"><article class="metric"><span>Всего инцидентов</span><strong>${m.total}</strong></article><article class="metric"><span>Критические</span><strong>${m.critical}</strong></article><article class="metric"><span>Потенциальный штраф</span><strong>${fmt(m.potentialFine)} ₽</strong></article><article class="metric"><span>Подтверждённые нарушения</span><strong>${incidents.filter(i=>i.result==="Подтверждённое нарушение").length}</strong></article></div><section class="panel" style="margin-bottom:16px"><div class="section-head"><div><h2>Необходимые действия</h2><p class="subtle">Топ-5 действий для предотвращения повторения нарушений</p></div><button class="button ghost" data-all-actions>Все действия</button></div><div class="actions-list">${actions.slice(0,5).map(actionRow).join("")}</div></section><section class="panel"><div class="section-head"><div><h2>Инциденты по типам нарушений</h2><p class="subtle">Только разобранные типы отклонений: INC-001, INC-002 и INC-006</p></div></div>${typeChart()}</section>`}
function storeFilter(){const all=[...new Set(incidents.map(i=>i.store))],label=!state.stores.length?"Все магазины":state.stores.length===1?state.stores[0]:`Магазины · ${state.stores.length}`;return `<details class="select multi-filter store-filter"><summary>${label} ⌄</summary><div class="multi-menu"><div class="multi-actions"><button type="button" data-store-all>Выбрать все</button><button type="button" data-store-clear>Сбросить</button></div>${all.map(x=>`<label><input type="checkbox" data-store-filter value="${x}" ${state.stores.includes(x)?"checked":""}>${x}</label>`).join("")}</div></details>`}
function typeFilter(){const all=[...new Set(incidents.map(i=>i.type))];return `<details class="select multi-filter"><summary>Тип нарушения${state.types.length?` · ${state.types.length}`:""} ⌄</summary><div class="multi-menu">${all.map(x=>`<label><input type="checkbox" data-type-filter value="${x}" ${state.types.includes(x)?"checked":""}>${x}</label>`).join("")}</div></details>`}
function renderIncidents(){const rows=filteredIncidents();qs("#incidents-view").innerHTML=`${pageHead("Инциденты",`Системные результаты анализа отклонений за ${dateRangeLabel()}`,`<button class="button" data-export>Выгрузить CSV</button>`)}${state.actionIncidentIds?`<section class="panel" style="margin-bottom:14px;padding:14px"><strong>Показаны инциденты, связанные с выбранным действием</strong><button class="button ghost" data-clear-action style="margin-left:12px">Показать все инциденты</button></section>`:""}<div class="filterbar">${dateRangeControl()}<input class="input search" id="search" type="search" placeholder="ШК, артикул или код маркировки — через запятую" value="${state.query}">${storeFilter()}${typeFilter()}<label class="check-filter"><input type="checkbox" id="priority-filter" ${state.priorityOnly?"checked":""}>Только критические</label><select class="select" id="result-filter"><option value="">Результат проверки: все</option>${[...new Set(incidents.map(i=>i.result))].map(x=>`<option ${state.result===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="table-wrap">${rows.length?`<table><thead><tr><th>Инцидент</th><th>Дата и время</th><th>Магазин / касса</th><th>Тип нарушения</th><th>Результат проверки</th><th>Потенциальный штраф</th><th></th></tr></thead><tbody>${rows.map(i=>`<tr class="${i.critical?"critical":""}" tabindex="0" data-incident="${i.id}"><td><span class="cell-title">${i.id}</span><span class="cell-sub">${i.rule} · ${i.group}</span></td><td>${i.time}</td><td><span class="cell-title">${i.store}</span><span class="cell-sub">${i.cash} · ${i.city}</span></td><td>${i.type}</td><td>${badge(i.result,i.result==="Подтверждённое нарушение"?"danger":"ok")}</td><td>${i.fine?`${fmt(i.fine)} ₽`:"—"}</td><td>›</td></tr>`).join("")}</tbody></table>`:`<div class="empty"><h3>Инциденты не найдены</h3></div>`}</div>`}
function renderIncident(id){const i=incidents.find(x=>x.id===id)||incidents[0];qs("#incident-view").innerHTML=`<button class="back" id="back-incidents">← Назад к списку инцидентов</button><div class="page-head"><div><div class="incident-title"><h1>${i.id}</h1>${i.critical?badge("Критический","danger"):""}</div><p>${i.type} · ${i.store}, ${i.cash}</p></div><div class="controls"><button class="button" data-copy>Копировать ссылку</button><button class="button" data-pdf>Описание для контролирующих органов, PDF</button></div></div><div class="incident-layout"><div><section class="panel summary-card"><span class="eyebrow">Результат проверки</span><div class="result-line"><div><strong>${i.result}</strong><p class="subtle">Правило ${i.rule} v0.1 · анализ завершён</p></div></div><div class="explain"><strong>Почему получен такой результат</strong><br>${i.reason}</div><dl class="kv"><dt>Операция</dt><dd>${i.time}</dd><dt>Номер чека / ID операции</dt><dd>${i.receipt}</dd><dt>Товар</dt><dd>${i.product}</dd><dt>Штрихкод</dt><dd>${i.barcode}</dd><dt>Артикул</dt><dd>${i.article}</dd><dt>Товарная группа</dt><dd>${i.group}</dd><dt>Код маркировки</dt><dd>${i.mark}</dd><dt>Источник проверки</dt><dd>${i.verificationSource}</dd><dt>Контур устранения</dt><dd>${i.contour}</dd><dt>Состояние</dt><dd>${i.status}</dd></dl><div class="tabs"><button class="tab ${state.tab==="analysis"?"active":""}" data-tab="analysis">Цепочка проверки</button><button class="tab ${state.tab==="source"?"active":""}" data-tab="source">Исходное отклонение</button><button class="tab ${state.tab==="operations"?"active":""}" data-tab="operations">Операции</button></div><div class="tab-content" id="tab-content"></div></section></div><aside><section class="panel side-card"><h3>Необходимое действие</h3><div class="recommendation">${i.recommendation}</div></section><section class="panel side-card"><h3>Критичность</h3><dl class="kv"><dt>Критичность</dt><dd>${i.critical?badge("Критическая","danger"):badge("Некритическая")}</dd><dt>Риск автоштрафа</dt><dd>${i.critical?"Да":"Нет"}</dd></dl></section></aside></div>`;renderTab(i)}
function renderTab(i){const c=qs("#tab-content");if(state.tab==="source")c.innerHTML=`<dl class="kv"><dt>Правило</dt><dd>${i.rule}</dd><dt>Вид отклонения</dt><dd>${i.sourceKind}</dd><dt>Описание</dt><dd>${i.sourceText}</dd></dl>`;else if(state.tab==="operations")c.innerHTML=`<dl class="kv"><dt>Документ продажи</dt><dd>Чек № ${i.id.slice(-4)}</dd><dt>Продажа завершена успешно</dt><dd>Да · ${i.time}</dd><dt>Код маркировки</dt><dd>${i.mark}</dd></dl>`;else c.innerHTML=i.chain.map((x,n)=>`<div class="evidence-step"><span class="step">${n+1}</span><div><strong>${x}</strong></div></div>`).join("")}
function renderActions(){qs("#actions-view").innerHTML=`${pageHead("Необходимые действия","Действия для предотвращения повторения нарушений",dateRangeControl())}<section class="panel" style="margin-top:20px"><div class="actions-list">${actions.map(actionRow).join("")}</div></section>`}
function renderAnalytics(){const rows=filteredIncidents(),start=dateAtStart(state.rangeStart),end=dateAtStart(state.rangeEnd),days=Math.round((end-start)/DAY)+1,byDay=days<=14,b=[];for(let c=new Date(start);c<=end;){const s=new Date(c),e=new Date(c);e.setDate(e.getDate()+(byDay?0:6));if(e>end)e.setTime(end.getTime());b.push({label:new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit"}).format(s),count:rows.filter(i=>{const d=incidentDate(i.time);return d>=s&&d<=e}).length});c=new Date(e);c.setDate(c.getDate()+1)}const m=Math.max(1,...b.map(x=>x.count));qs("#analytics-view").innerHTML=`${pageHead("Аналитика","Динамика нарушений",dateRangeControl())}<section class="panel"><div class="chart">${b.map(x=>`<div class="col" style="height:${Math.max(10,x.count/m*100)}%"><b>${x.count}</b><span>${x.label}</span></div>`).join("")}</div></section>`}
function renderSettings(){qs("#settings-view").innerHTML=`${pageHead("Настройки мониторинга","Доступно администраторам Set Mark")}<section class="panel" style="margin-top:20px"><h2>Источники данных</h2><div class="setting-row"><div><strong>Интеграция с API Честного Знака</strong><small>Получение отклонений</small></div>${badge("Деморежим","warn")}</div><div class="setting-row"><div><strong>Данные кассового ПО</strong><small>Результаты проверок и фактическое действие</small></div>${badge("Доступно","ok")}</div></section>`}
function csvCell(v){return `"${String(v??"").replaceAll('"','""')}"`}
function exportCsv(){const r=filteredIncidents(),headers=["ID инцидента","Код правила","Дата и время операции","Магазин","Город","Касса","Штрихкод","Артикул","Наименование товара","Товарная группа","Полный код маркировки","Тип нарушения","Описание исходного отклонения","Результат проверки","Критичность","Риск автоштрафа","Потенциальная сумма штрафа","Установленная причина","Рекомендуемое действие","Контур устранения","Статус анализа","Номер чека / ID операции","Источник проверки"],rows=r.map(i=>[i.id,i.rule,i.time,i.store,i.city,i.cash,i.barcode,i.article,i.product,i.group,i.mark,i.type,i.sourceText,i.result,i.critical?"Критическая":"Некритическая",i.critical?"Да":"Нет",i.fine,i.reason,i.recommendation,i.contour,i.status,i.receipt,i.verificationSource]),csv=[headers,...rows].map(row=>row.map(csvCell).join(";")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="set-mark-incidents-expanded.csv";a.click()}
function bind(){qsa("[data-export]").forEach(x=>x.onclick=exportCsv);qsa("[data-range-preset]").forEach(x=>x.onchange=()=>x.value==="custom"?(state.rangePreset="custom",route()):applyPreset(x.value));qsa("[data-apply-range]").forEach(x=>x.onclick=()=>{const p=x.closest(".date-range");state.rangeStart=p.querySelector("[data-range-start]").value;state.rangeEnd=p.querySelector("[data-range-end]").value;state.rangePreset="custom";route()});qsa("[data-action-incidents]").forEach(x=>{const go=()=>{state.actionIncidentIds=x.dataset.actionIncidents.split(",");state.query="";state.stores=[];state.types=[];state.priorityOnly=false;state.result="";navigate("incidents")};x.onclick=go;x.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")go()}});qsa("[data-clear-action]").forEach(x=>x.onclick=()=>{state.actionIncidentIds=null;renderIncidents();bind()});qsa("[data-all-actions]").forEach(x=>x.onclick=()=>navigate("actions"));qsa("[data-type-jump]").forEach(x=>x.onclick=()=>{state.types=[x.dataset.typeJump];navigate("incidents")});qsa("[data-priority]").forEach(x=>x.onclick=()=>{state.priorityOnly=true;navigate("incidents")});qsa("[data-incident]").forEach(x=>x.onclick=()=>navigate("incident/"+x.dataset.incident));qsa("[data-tab]").forEach(x=>x.onclick=()=>{state.tab=x.dataset.tab;renderIncident(location.hash.split("/")[1])});const s=qs("#search");if(s)s.oninput=e=>{state.query=e.target.value;renderIncidents();bind()};qsa("[data-store-filter]").forEach(x=>x.onchange=e=>{state.stores=e.target.checked?[...state.stores,e.target.value]:state.stores.filter(s=>s!==e.target.value);renderIncidents();bind()});qsa("[data-store-all]").forEach(x=>x.onclick=()=>{state.stores=[...new Set(incidents.map(i=>i.store))];renderIncidents();bind()});qsa("[data-store-clear]").forEach(x=>x.onclick=()=>{state.stores=[];renderIncidents();bind()});const p=qs("#priority-filter");if(p)p.onchange=e=>{state.priorityOnly=e.target.checked;renderIncidents();bind()};const r=qs("#result-filter");if(r)r.onchange=e=>{state.result=e.target.value;renderIncidents();bind()};qsa("[data-type-filter]").forEach(x=>x.onchange=e=>{state.types=e.target.checked?[...state.types,e.target.value]:state.types.filter(t=>t!==e.target.value);renderIncidents();bind()});const back=qs("#back-incidents");if(back)back.onclick=()=>navigate("incidents")}
function route(){const [p,id]=(location.hash||"#overview").slice(1).split("/");qsa(".view").forEach(v=>v.hidden=true);qsa("[data-nav]").forEach(a=>a.classList.toggle("active",a.dataset.nav===p));if(p==="incidents"){renderIncidents();qs("#incidents-view").hidden=false}else if(p==="incident"){renderIncident(id);qs("#incident-view").hidden=false}else if(p==="actions"){renderActions();qs("#actions-view").hidden=false}else if(p==="analytics"){renderAnalytics();qs("#analytics-view").hidden=false}else if(p==="settings"){renderSettings();qs("#settings-view").hidden=false}else{renderOverview();qs("#overview-view").hidden=false}bind();window.scrollTo(0,0)}window.addEventListener("hashchange",route);route();