from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_VERSION = '4.4'
PRODUCT_VERSION = '4.4'
PHASE_SEQUENCE = [
    'SOURCE_SETUP',
    'INTAKE',
    'PRODUCT_DEFINITION',
    'VISUAL_PROTOTYPE',
    'VISUAL_VALIDATION',
    'WORKING_PROTOTYPE',
    'WORKING_VALIDATION',
    'HANDOFF_READY',
]

# Legacy aliases are accepted on read and removed on the next save. This lets
# 4.3 open projects generated by 4.0-4.2 without KeyError failures.
TOP_LEVEL_ALIASES: dict[str, dict[str, tuple[str, ...]]] = {
    'product/evidence-register.json': {'evidence': ('evidenceEntries', 'entries')},
    'product/artifact-evidence.json': {'evidence': ('evidenceEntries', 'entries')},
    'product/phase-reviews.json': {'reviews': ('reviewEntries', 'entries')},
    'product/open-questions.json': {'questions': ('questionEntries', 'entries')},
    'product/requirements-index.json': {
        'requirements': ('requirementEntries',),
        'needsInput': ('needsInputs', 'needInputs'),
        'errors': ('validationErrors',),
    },
    'product/requirements-baseline.json': {'baselines': ('baselineEntries', 'entries')},
    'sources/source-manifest.json': {'entries': ('sources', 'sourceEntries')},
}


def configure_utf8_output() -> None:
    """Make Cyrillic CLI output reliable in PowerShell, cmd, macOS and Linux.

    Python's Windows console is Unicode-aware, but redirected output and older
    shells can inherit a legacy code page. Reconfiguring both streams prevents
    UnicodeEncodeError and makes subprocess output deterministic UTF-8.
    """
    for name in ('stdout', 'stderr'):
        stream = getattr(sys, name, None)
        if stream is not None and hasattr(stream, 'reconfigure'):
            try:
                stream.reconfigure(encoding='utf-8', errors='replace')
            except (AttributeError, OSError, ValueError):
                pass


configure_utf8_output()


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _normalize_top_level(rel: str, obj):
    if not isinstance(obj, dict):
        return obj
    aliases = TOP_LEVEL_ALIASES.get(Path(rel).as_posix(), {})
    normalized = dict(obj)
    for canonical, legacy_keys in aliases.items():
        if canonical not in normalized:
            for legacy in legacy_keys:
                if legacy in normalized:
                    normalized[canonical] = normalized[legacy]
                    break
        for legacy in legacy_keys:
            if legacy != canonical:
                normalized.pop(legacy, None)
    normalized['schemaVersion'] = SCHEMA_VERSION
    return normalized


def _normalize_evidence_item(item: dict) -> dict:
    normalized = dict(item)
    if not normalized.get('id') and normalized.get('evidenceId'):
        normalized['id'] = normalized.pop('evidenceId')
    else:
        normalized.pop('evidenceId', None)
    if not normalized.get('snapshotPath') and normalized.get('snapshotFile'):
        normalized['snapshotPath'] = normalized.pop('snapshotFile')
    else:
        normalized.pop('snapshotFile', None)
    evidence_id = str(normalized.get('id') or '')
    if not normalized.get('type'):
        if evidence_id.startswith('SRC-EV-'):
            normalized['type'] = 'SOURCE_EXCERPT'
        elif evidence_id.startswith('PM-DEC-'):
            normalized['type'] = 'PRODUCT_MANAGER_DECISION'
        elif evidence_id.startswith('AI-PROP-'):
            normalized['type'] = 'AI_PROPOSAL'
    if not normalized.get('createdAt'):
        normalized['createdAt'] = normalized.get('verifiedAt') or now()
    if not normalized.get('recordedBy'):
        normalized['recordedBy'] = 'legacy-migration'
    if normalized.get('domainId') and not normalized.get('domainIds'):
        normalized['domainIds'] = [normalized['domainId']]
    if isinstance(normalized.get('domainIds'), str):
        normalized['domainIds'] = [normalized['domainIds']]
    normalized.pop('verifiedAt', None)
    return normalized


def normalize_document(rel: str, obj):
    rel = Path(rel).as_posix()
    normalized = _normalize_top_level(rel, obj)
    if not isinstance(normalized, dict):
        return normalized
    if rel == 'product/evidence-register.json':
        normalized['evidence'] = [
            _normalize_evidence_item(item) if isinstance(item, dict) else item
            for item in normalized.get('evidence', [])
        ]
    return normalized


def load(rel: str):
    path = ROOT / rel
    try:
        obj = json.loads(path.read_text(encoding='utf-8-sig'))
    except FileNotFoundError:
        raise SystemExit(f'JSON-файл не найден: {rel}')
    except json.JSONDecodeError as exc:
        raise SystemExit(f'Некорректный JSON {rel}: строка {exc.lineno}, столбец {exc.colno}: {exc.msg}')
    return normalize_document(rel, obj)


def save(rel: str, obj, *, validate: bool = True) -> None:
    rel = Path(rel).as_posix()
    obj = normalize_document(rel, obj)
    if validate:
        from json_contracts import validate_document

        # Fast structural checks run before every atomic write. Full JSON Schema
        # validation is performed by sync_workspace --strict-json and validate_workspace.
        contract_errors = validate_document(rel, obj, strict_items=True, use_schema=False)
        if contract_errors:
            raise SystemExit('Нельзя записать некорректный JSON ' + rel + ':\n' + '\n'.join(contract_errors))
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(obj, ensure_ascii=False, indent=2) + '\n'
    # Atomic replacement avoids half-written registries after interruption.
    fd, temp_name = tempfile.mkstemp(prefix=path.name + '.', suffix='.tmp', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'w', encoding='utf-8', newline='\n') as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        attempts = 6 if rel in {
            'product/requirements-index.json', 'product/phase-reviews.json',
            'product/completeness-report.json', 'product/artifact-evidence.json'
        } else 3
        delay = 0.05
        last_error = None
        for attempt in range(attempts):
            try:
                os.replace(temp_name, path)
                last_error = None
                break
            except PermissionError as exc:
                last_error = exc
                if attempt < attempts - 1:
                    time.sleep(delay)
                    delay = min(delay * 2, 0.8)
        if last_error is not None:
            raise SystemExit(f'Не удалось атомарно записать {rel}: {last_error}')
    finally:
        if os.path.exists(temp_name):
            try:
                os.unlink(temp_name)
            except PermissionError:
                pass


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def directory_sha256(path: Path, *, ignored_names: set[str] | None = None) -> str | None:
    ignored_names = ignored_names or set()
    files = sorted(
        item for item in path.rglob('*')
        if item.is_file() and item.name not in ignored_names and '__pycache__' not in item.parts
    )
    if not files:
        return None
    digest = hashlib.sha256()
    for item in files:
        digest.update(item.relative_to(path).as_posix().encode('utf-8'))
        digest.update(b'\0')
        digest.update(hashlib.sha256(item.read_bytes()).digest())
    return digest.hexdigest()


def artifact_sha256(path: Path) -> str:
    """Hash a file or directory exactly as artifact evidence records it."""
    if path.is_file():
        return sha256(path)
    digest = directory_sha256(path)
    if not digest:
        raise SystemExit(f'Каталог артефакта пуст: {path}')
    return digest


def next_id(prefix: str, items: list[dict]) -> str:
    numbers = []
    for item in items:
        item_id = item.get('id') or item.get('evidenceId') or ''
        match = re.fullmatch(re.escape(prefix) + r'-(\d+)', str(item_id))
        if match:
            numbers.append(int(match.group(1)))
    return f'{prefix}-{max(numbers or [0]) + 1:03d}'


def project_path(rel: str, *, must_exist: bool = False, allowed_root: str | None = None) -> Path:
    """Resolve a project-relative path and reject absolute/path-traversal values."""
    raw = Path(rel)
    if raw.is_absolute():
        raise SystemExit('Разрешены только относительные пути внутри проекта')
    resolved = (ROOT / raw).resolve()
    base = (ROOT / allowed_root).resolve() if allowed_root else ROOT.resolve()
    try:
        resolved.relative_to(base)
    except ValueError:
        raise SystemExit(f'Путь должен находиться внутри {allowed_root or "проекта"}')
    if must_exist and not resolved.exists():
        raise SystemExit(f'Файл не найден: {rel}')
    return resolved


def phase_at_least(current: str, required: str) -> bool:
    return PHASE_SEQUENCE.index(current) >= PHASE_SEQUENCE.index(required)


def evidence_domains(item: dict) -> set[str]:
    domains = set(item.get('domainIds') or [])
    if item.get('domainId'):
        domains.add(item['domainId'])
    return {str(value) for value in domains if value}


def evidence_applies_to(item: dict, domain_id: str) -> bool:
    domains = evidence_domains(item)
    return domain_id in domains or '*' in domains


def run_tool(
    script: str,
    args: Iterable[str] = (),
    *,
    allowed_returncodes: set[int] | None = None,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    """Run another Product Compiler tool with deterministic UTF-8 I/O."""
    allowed_returncodes = allowed_returncodes or {0}
    merged_env = os.environ.copy()
    merged_env.setdefault('PYTHONUTF8', '1')
    merged_env.setdefault('PYTHONIOENCODING', 'utf-8')
    if env:
        merged_env.update(env)
    result = subprocess.run(
        [sys.executable, str(ROOT / 'tools' / script), *[str(value) for value in args]],
        cwd=ROOT,
        capture_output=True,
        encoding='utf-8',
        errors='replace',
        env=merged_env,
        check=False,
    )
    if result.returncode not in allowed_returncodes:
        message = (result.stdout or '') + (result.stderr or '')
        raise SystemExit(f'{script} завершился с кодом {result.returncode}\n{message}'.rstrip())
    return result


def latest_review_for_phase(reviews: list[dict], phase: str, review_id: str | None = None) -> dict | None:
    candidates = [item for item in reviews if item.get('phase') == phase and item.get('status') != 'SUPERSEDED']
    if review_id:
        return next((item for item in candidates if item.get('reviewId') == review_id), None)
    if not candidates:
        return None
    return max(candidates, key=lambda item: int(item.get('revision') or 0))


def normalize_snapshot_relpath(value: str | None) -> str | None:
    if not value:
        return None
    path = Path(str(value).replace('\\', '/'))
    parts = path.parts
    if parts and parts[0] == 'snapshots':
        path = Path('sources') / path
    return path.as_posix()


def source_snapshot_record(source: dict, snapshot_path: str) -> dict | None:
    """Find a registered top-level or descendant snapshot by normalized path."""
    target = normalize_snapshot_relpath(snapshot_path)
    candidates = [source, *(source.get('descendants') or [])]
    for candidate in candidates:
        candidate_path = normalize_snapshot_relpath(candidate.get('snapshotPath') or candidate.get('snapshotFile'))
        if candidate_path == target:
            return candidate
    return None


def mark_phase_reviews_stale(phase: str, reason: str) -> list[str]:
    doc = load('product/phase-reviews.json')
    changed = []
    for item in doc.get('reviews', []):
        if item.get('phase') == phase and item.get('status') in {'READY_FOR_REVIEW', 'APPROVED'}:
            item['status'] = 'STALE_REVIEW'
            item['staleAt'] = now()
            item['staleReason'] = reason
            changed.append(str(item.get('reviewId')))
    if changed:
        save('product/phase-reviews.json', doc)
    return changed
